spring:
  data:
    mongodb:
      username: noone
      password: passer1234
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
